In [1]:
def solution(year):
    return (year-1) // 100 + 1

In [2]:
solution(1700)

17

In [3]:
foo = "01234567"
# foo[-3:]
foo[3:-2:1]
# foo[::-1]

'345'

In [4]:
def palendrome(inputString):
    return inputString[::-1] == inputString

palendrome("012210")

True

In [5]:
list(range(0,4))

[0, 1, 2, 3]

In [6]:
def greatest_pair_product(inputArray):
    from decimal import Decimal
    top_prod = Decimal('-Infinity')
    for idx in range(0,len(inputArray)-1):
        print(inputArray[idx:idx+2])
        prod = inputArray[idx] * inputArray[idx+1]
        print(prod)
        if prod > top_prod:
            top_prod = prod
    return top_prod

# greatest_pair_product([0,1,2,3,0])
greatest_pair_product( [-23, 4, -3, 8, -12])


[-23, 4]
-92
[4, -3]
-12
[-3, 8]
-24
[8, -12]
-96


-12

In [7]:
def uniques_count(n):
    s = 0
    for x in range(n):
        print(x)
        s += x
    return s

uniques = uniques_count(4)
total = 1 + 4*uniques
return total


0
1
2
3


SyntaxError: 'return' outside function (1735327824.py, line 10)

In [ ]:
x = [1,3,2]
x.sort()
x

[1, 2, 3]

In [ ]:
def count_gaps_in_sequence(statues):
    statues.sort()
    gap_sum = 0
    for idx in range(0, len(statues)-1):
        # print(statues[idx])
        # print(statues[idx + 1] - statues[idx])
        gap_sum += statues[idx + 1] - statues[idx] - 1

    return gap_sum

x = [1,3,0,2, 5]
count_gaps_in_sequence(x)

1

In [ ]:
foo = [0,1,2,3]
foo[1:2]


[1]

In [ ]:
def pad_sequence(sequence):
    # prep the array by inserting a first/last token which satisfies...
    return [sequence[0]-1] + sequence + [sequence[-1]+1]

print(pad_sequence([0,1,2,3]))
          

[-1, 0, 1, 2, 3, 4]


In [ ]:
def strictly_increasing_or_failing_boundary(sequence):
    for idx in range(len(sequence) - 1):
        if sequence[idx]+1 != sequence[idx+1]:
            return [False, idx, idx+1]
    return [True, -1, -1]

strictly_increasing_or_failing_boundary([10,11,11,12])

[False, 1, 2]

In [ ]:
def strictly_increasing_sequence(sequence):
    # print(f"input {sequence}")
  
    # sequence.sort()

    def strictly_increasing_or_failing_boundary(sequence):
        for idx in range(len(sequence) - 1):
            # print(f"{sequence[idx]} {sequence[idx+1]} {sequence[idx] >= sequence[idx+1]}")
            if sequence[idx] >= sequence[idx+1]:
                return [False, idx, idx+1]
        return [True, -1, -1]

    def pad_sequence(sequence):
        # prep the array by inserting a first/last token which satisfies...
        return [sequence[0]-1] + sequence + [sequence[-1]+1]

    def sub_sequence_removing(sequence, bad_idx):
        return sequence[:bad_idx] + sequence[bad_idx+1:]

    sequence1 = pad_sequence(sequence)
    chk, idx_a, idx_b = strictly_increasing_or_failing_boundary(sequence1)
    idx_a -= 1
    idx_b -= 1
    # print(f"idx_a {idx_a} idx_b {idx_b}")
    if chk:
        return True

    # print(f"attempting remove {sequence[idx_a]}")    
    sequence2 = pad_sequence(sub_sequence_removing(sequence, idx_a))
    chk, _, _ = strictly_increasing_or_failing_boundary(sequence2)
    if chk:
        return True
    
    # print(f"attempting remove {sequence[idx_b]}")    
    sequence3 = pad_sequence(sub_sequence_removing(sequence, idx_b))
    chk, _, _ = strictly_increasing_or_failing_boundary(sequence3)
    if chk:
        return True
    
    return False


print(strictly_increasing_sequence([10,11,12,13,14]))
print(strictly_increasing_sequence([10,16,11,12,13]))
print(strictly_increasing_sequence([10,11,11,12,13]))
print(strictly_increasing_sequence([11,11,12,13,14]))
print(strictly_increasing_sequence([10,11,12,13,13]))
print(strictly_increasing_sequence([10,1,2,3,4,5]))

print(strictly_increasing_sequence([0, -2, 5, 6]))

print(strictly_increasing_sequence([1,3,2]))



input [10, 11, 12, 13, 14]
True
input [10, 16, 11, 12, 13]
True
input [10, 11, 11, 12, 13]
True
input [11, 11, 12, 13, 14]
True
input [10, 11, 12, 13, 13]
True
input [10, 1, 2, 3, 4, 5]
True
input [0, -2, 5, 6]
True
input [1, 3, 2]
True


In [ ]:
def matrix_elements_sum_above_zero_values(matrix):

    import numpy as np
    print(f"input {matrix}")
    matrix_np = np.array(matrix).T
    # matrix_np.T
    print(matrix_np)
    # rows = len(matrix)
    # cols = len(matrix[0])
    # print(f"rows {rows} cols {cols}")

    sum = 0
    for row in matrix_np:
        for element in row:
            if element == 0:
                break
            sum += element

    return sum

matrix = [[1, 1, 1, 0], 
          [0, 5, 0, 1], 
          [2, 1, 3, 10]]

print(matrix_elements_sum_above_zero_values(matrix))



input [[1, 1, 1, 0], [0, 5, 0, 1], [2, 1, 3, 10]]
[[ 1  0  2]
 [ 1  5  1]
 [ 1  0  3]
 [ 0  1 10]]
9


In [ ]:
ks = set()
ks.add("foo")
type(ks)

set

In [12]:
def longest_strings(inputArray):

    max_len = 0
    keeper_list = []
    
    for element in inputArray:
        if len(element) > max_len:
            max_len = len(element)
            keeper_list = [element]
        elif len(element) == max_len:
            keeper_list.append(element)

    return list(keeper_list)

# print(longest_strings(["aba", "aa", "ad", "vcd", "aba"]))
print(longest_strings(["aba", "aa", "ad", "vcd", "aba"]))

['aba', 'vcd', 'aba']


In [13]:
set('aabc')

{'a', 'b', 'c'}

In [18]:
type({'aabc'})

set

In [29]:
def common_characters(s1, s2):
    set1 = set(s1)
    set2 = set(s2)
    s1_u_s2 = set1.union(set2)
    print(s1_u_s2)

    count_s1 = {}
    count_s2 = {}
    for k in s1_u_s2:
        count_s1[k]= s1.count(k)
        count_s2[k]= s2.count(k)

    print(count_s1)
    print(count_s2)

    total = 0
    for k in s1_u_s2:
        if count_s1[k] <= count_s2[k]:
            total += count_s1[k]
        else:
            total += count_s2[k]
    return total

print(common_characters('aabc', 'bbcd'))


{'a', 'd', 'c', 'b'}
{'a': 2, 'd': 0, 'c': 1, 'b': 1}
{'a': 0, 'd': 1, 'c': 1, 'b': 2}
2


In [33]:
foo = str(1234)
hlen = len(foo)//2

print(foo[:hlen])
print(foo[hlen:])

12
34


In [36]:
def is_lucky(n):
    str_n = str(n)
    hlen = len(foo)//2
    str_left = str_n[:hlen]
    str_right = str_n[hlen:]

    sum_left = 0
    sum_right = 0
    for idx in range(hlen):
        sum_left += int(str_left[idx])
        sum_right += int(str_right[idx])
    
    return sum_left == sum_right

is_lucky(1230)

True